export const MARY_HAD_A_LITTLE_LAMB = {
  title: "Mary Had a Little Lamb",
  timeSignature: [4, 4],
  keySignature: "C",
  tempo: 100,
  notes: [
    { pitch: "E4", duration: "4n", measure: 1, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 1, beat: 2 },
    { pitch: "C4", duration: "4n", measure: 1, beat: 3 },
    { pitch: "D4", duration: "4n", measure: 1, beat: 4 },
    { pitch: "E4", duration: "4n", measure: 2, beat: 1 },
    { pitch: "E4", duration: "4n", measure: 2, beat: 2 },
    { pitch: "E4", duration: "2n", measure: 2, beat: 3 },
    { pitch: "D4", duration: "4n", measure: 3, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 3, beat: 2 },
    { pitch: "D4", duration: "2n", measure: 3, beat: 3 },
    { pitch: "E4", duration: "4n", measure: 4, beat: 1 },
    { pitch: "G4", duration: "4n", measure: 4, beat: 2 },
    { pitch: "G4", duration: "2n", measure: 4, beat: 3 },
    { pitch: "E4", duration: "4n", measure: 5, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 5, beat: 2 },
    { pitch: "C4", duration: "4n", measure: 5, beat: 3 },
    { pitch: "D4", duration: "4n", measure: 5, beat: 4 },
    { pitch: "E4", duration: "4n", measure: 6, beat: 1 },
    { pitch: "E4", duration: "4n", measure: 6, beat: 2 },
    { pitch: "E4", duration: "4n", measure: 6, beat: 3 },
    { pitch: "E4", duration: "4n", measure: 6, beat: 4 },
    { pitch: "D4", duration: "4n", measure: 7, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 7, beat: 2 },
    { pitch: "E4", duration: "4n", measure: 7, beat: 3 },
    { pitch: "D4", duration: "4n", measure: 7, beat: 4 },
    { pitch: "C4", duration: "1n", measure: 8, beat: 1 },
  ],
};

export const TWINKLE_TWINKLE = {
  title: "Twinkle Twinkle Little Star",
  timeSignature: [4, 4],
  keySignature: "C",
  tempo: 90,
  notes: [
    { pitch: "C4", duration: "4n", measure: 1, beat: 1 },
    { pitch: "C4", duration: "4n", measure: 1, beat: 2 },
    { pitch: "G4", duration: "4n", measure: 1, beat: 3 },
    { pitch: "G4", duration: "4n", measure: 1, beat: 4 },
    { pitch: "A4", duration: "4n", measure: 2, beat: 1 },
    { pitch: "A4", duration: "4n", measure: 2, beat: 2 },
    { pitch: "G4", duration: "2n", measure: 2, beat: 3 },
    { pitch: "F4", duration: "4n", measure: 3, beat: 1 },
    { pitch: "F4", duration: "4n", measure: 3, beat: 2 },
    { pitch: "E4", duration: "4n", measure: 3, beat: 3 },
    { pitch: "E4", duration: "4n", measure: 3, beat: 4 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 2 },
    { pitch: "C4", duration: "2n", measure: 4, beat: 3 },
  ],
};

export const HOT_CROSS_BUNS = {
  title: "Hot Cross Buns",
  timeSignature: [4, 4],
  keySignature: "C",
  tempo: 100,
  notes: [
    { pitch: "E4", duration: "4n", measure: 1, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 1, beat: 2 },
    { pitch: "C4", duration: "2n", measure: 1, beat: 3 },
    { pitch: "E4", duration: "4n", measure: 2, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 2, beat: 2 },
    { pitch: "C4", duration: "2n", measure: 2, beat: 3 },
    { pitch: "C4", duration: "4n", measure: 3, beat: 1 },
    { pitch: "C4", duration: "4n", measure: 3, beat: 2 },
    { pitch: "C4", duration: "4n", measure: 3, beat: 3 },
    { pitch: "C4", duration: "4n", measure: 3, beat: 4 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 2 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 3 },
    { pitch: "D4", duration: "4n", measure: 4, beat: 4 },
    { pitch: "E4", duration: "4n", measure: 5, beat: 1 },
    { pitch: "D4", duration: "4n", measure: 5, beat: 2 },
    { pitch: "C4", duration: "2n", measure: 5, beat: 3 },
  ],
};

export const ALL_DEMOS = [MARY_HAD_A_LITTLE_LAMB, TWINKLE_TWINKLE, HOT_CROSS_BUNS];
